### ISSUE TITLE
Allow test data to be downloaded from google drive

### ISSUE THREAD

**Issue by graeme-winter** [dials/data#138]
Dependency += `gdown`

Example code snippet:

```
import gdown

files = {"indexed.refl":"1iXejo0YSBpBq_WezDnz4bKuA4CpVE0dz",
         "indexed.expt":"145e0pSGSYtu5uZ9pfvyXwhWnhklkAA-m"}

for out in files:
    fid = files[out]

    gdown.download("https://drive.google.com/uc?id=%s" % fid, out, quiet=True)
```

would make it very easy to fetch data down from somewhere where people can easily add

**Comment by graeme-winter** [comment]
Question rephrase: should we allow `dials_data` to download data from Google Drive? As alternative to http download from $interweb

**Comment by dagewa** [comment]
I think my points still stand

**Comment by graeme-winter** [comment]
So the feeling is that our test data should only be used if it is sufficiently valuable to publish online as a data set in its own right? I'm not sure I share the perspective but I asked for opinions, so I won't disagree.

**Comment by dagewa** [comment]
No, I think that's an overreach. My concern with google drive is: whose google drive? How do I ensure my tests run if the data are deleted? Are there copies elsewhere? Recently the owner of a shared google folder deleted this folder including information I was using. It disappeared forever. Even the owner could not retrieve. I think this is not a suitable place for shared test data

**Comment by graeme-winter** [comment]
In this context I recognise your reluctance to this - and I asked for opinions - however a lighter weight solution than publishing each test case as a zenodo repo would be appreciated. Thoughts?

**Comment by dagewa** [comment]
For small sets, push straight to https://github.com/dials/data-files @Anthchirp what are the space limitations?

**Comment by graeme-winter** [comment]
@dagewa can work with this for the mo 🙂 thanks

**Comment by rjgildea** [comment]
https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota#file-and-repository-size-limitations

> We recommend repositories be kept under 1GB each. Repositories have a hard limit of 100GB. If you reach 75GB you'll receive a warning from Git in your terminal when you push. This limit is easy to stay within if large files are kept out of the repository. If your repository exceeds 1GB, you might receive a polite email from GitHub Support requesting that you reduce the size of the repository to bring it back down.
>
> In addition, we place a strict limit of files exceeding 100 MB in size. For more information, see "Working with large files."

I believe @Anthchirp has previously suggested that if we do hit the 1GB repository limit, there is nothing to stop us just creating a new dials/data-files-2 repo for additional files.

**Comment by Anthchirp** [comment]
Github: 
> We recommend repositories be kept under 1GB each. Repositories have a hard limit of 100GB. If you reach 75GB you'll receive a warning from Git in your terminal when you push. This limit is easy to stay within if large files are kept out of the repository.

Upside:
* easy command line access

Downside:
* to add stuff you need to checkout everything that is currently there (even if you sparse checkout)
* old stuff never goes away again
* granted we could address both points with clever use of branches, but that makes it more complicated.
