### ISSUE TITLE
Documentation refers to both `dials_data` and `dials-data`

### ISSUE THREAD

**Issue by elena-pascal** [dials/data#403]
And I'm pretty sure there is also a `dials.data`. Maybe even a `dials/data`. I think the most consistent package name is 'dials-data' (while pip is happy to understand `dials_data` conda is not) but github repo and pytest fixture are `dials_data`. 

I'm trying to move all package references to `dials-data`in #400, but not sure that reduces entropy.

**Comment by dagewa** [comment]
This is largely (or fully) fixed by #400
