### ISSUE TITLE
refinement_test_data needs a directory structure

### ISSUE THREAD

**Issue by dagewa** [dials/data#410]
The `refinement_test_data` directory on [data-files](https://github.com/dials/data-files/tree/master/refinement_test_data) has sub-directories to mirror the original files on `dials_regression`. I forgot about that when adding [the definition](https://github.com/dials/data/blob/master/dials_data/definitions/refinement_test_data.yml), so the resulting dials-data dataset is missing some files, which have shared file names.

Is it possible to define the directory structure? I note the `spring8_ccp4_2018` dataset does this, but by downloading and unpacking a tar archive.

**Comment by dagewa** [comment]
Briefly looked at this. If we are going to allow directory structure in datasets then we'll have to do something different here https://github.com/dials/data/blob/d2990256cfb1bbe1e7ed98f27b60bb35d6e16792/dials_data/download.py#L143

**Comment by rjgildea** [comment]
Would it not make sense to split these up into multiple definitions, since there isn't much to group all these files together other than they happen to be used in some form of refinement tests?

**Comment by dagewa** [comment]
Yeah, happy to do that. It's the simplest solution.

**Comment by dagewa** [comment]
In some cases, I think I can just give the files more descriptive, and unique, names on https://github.com/dials/data-files and then leave them in a single definition for miscellaneous refinement test data

**Comment by dagewa** [comment]
Hmm, also I see that the files in `refinement_test_data/centroid` are ultimately sourced from the same dataset as the for the `centroid_test_data.yml` definition ("X4 lots"), so in that case I can just extend that definition instead.
