### ISSUE TITLE
Out of date version number in repo vs PyPI?

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/data#43]
@Anthchirp, I seem to be having trouble with dials_data versions when running [this test](https://github.com/dials/dials/blob/b1acc0de527b00b32ce88d37e1e54bef810a32c3/test/command_line/test_search_beam_position.py#L193) (though Jenkins seems to be fine, instead falling over at the expected values of beam shift, which I was trying to look into).  My dials_data is installed from a clone of the dials_data repo, with libtbx.pip install -e <dials_data directory>.  My copy seems to be up to date, but I have a version number `1.0.0-dev` < `1.0.5`, so Pytest complains:
```
$ libtbx.pip show dials_data
Name: dials-data
Version: 1.0.0
Summary: DIALS Regression Data Manager
Home-page: https://github.com/dials/data
Author: Markus Gerstel
Author-email: dials-support@lists.sourceforge.net
License: BSD license
Location: /home/ekm22040/DIALS/data
Requires: pytest, pyyaml, setuptools, six
Required-by:
```
```
$ dials.data
usage: dials.data <command> [<args>]

DIALS regression data manager v1.0.0-dev

<...etc.>
```
Meanwhile, there appear to be several newer versions listed on the PyPI:
```
$ libtbx.pip install dials_data==
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting dials_data==
  Could not find a version that satisfies the requirement dials_data== (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13)
No matching distribution found for dials_data==
```
I notice that the module's ```__version__``` hasn't changed since 63ca7a6.  Should this be bumped to 1.0.13 now, and then bumped by Travis with each _update file information_ PR?

**Comment by Anthchirp** [comment]
I think the solution should be to not install `dials_data` from source when _using_ `dials_data`, and checking out a separate copy into a virtual environment when _developing_ `dials_data`.

Having said that, it might still be possible to infer the correct version number on the fly when working off a checked-out copy of `dials_data`.
(In any case pytest shouldn't complain-complain, but just skip the test pointing out that your `dials_data`-version is out of date.)

I don't think Travis should ever change `__version__` in the source, that should be a conscious developer decision. It's of course perfectly reasonable to bump that for any reason or no reason in particular. Any such version changes should however be accompanied by an entry in the changelog.
