### ISSUE TITLE
Get data directory path via command line

### ISSUE THREAD

**Issue by rjgildea** [dials/data#55]
It would be useful to have a way to get the directory path for a given dials.data dataset. Essentially, a simpler way of facilitating command lines such as:

`$ xia2.multiplex $(dials.data get multi_crystal_proteinase_k | grep : | cut -d: -f 2)/multi_crystal_proteinase_k/*`

**Comment by Anthchirp** [comment]
=> `$ xia2.multiplex $(dials.data get -q multi_crystal_proteinase_k)/*`
